export const ActivityPoints = {
  ATTENDANCE: 5,
  WEEKLY_MODULE: 10,
  CERTIFICATION: 50,
  PROJECT_MILESTONE: 25,
  HELPING_PEER: 5,
  HACKATHON: 25,
  INTERNSHIP_OFFER: 100,
  GITHUB_PUBLISH: 10,
  WIN_CHALLENGE: 10,
  EVENT_ATTENDED: 10,
} as const;

export const MAX_POINTS_PER_MEMBER = 250;
export const MEMBERS_PER_PLG = 5;
export const MAX_POINTS_PER_PLG = MAX_POINTS_PER_MEMBER * MEMBERS_PER_PLG; // 1250


